WebDangKyKHHT/Areas/Admin/Controllers/ThongKeAdminController.cs
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Web.Mvc;
using WebDangKyKHHT.Models;



namespace WebDangKyKHHT.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ThongKeAdminController : Controller
    {
        SEP_TEAM15_WEBKHHTEntities model = new SEP_TEAM15_WEBKHHTEntities();
        // GET: ThongKe
        public ActionResult ThongKeChiTiet()
        {
            var thongkechitiet = model.KHHTs.OrderByDescending(x => x.ID).ToList();
            return View(thongkechitiet);
        } 
        public ActionResult Print(int id)
        {
            var printData = model.KHHTs.FirstOrDefault(x => x.ID == id);
            return View(printData);
        }
        public ActionResult Index()
        {
            var dlhk = model.HocKis.ToList();
            List<SelectListItem> idhk = new List<SelectListItem>();
            idhk.Add(new SelectListItem { Value = "", Text = "--Chọn học kì--", Selected = true });
            foreach (var item in dlhk)
            {
                idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
            }
            ViewBag.ID_HK = idhk;
            //ViewBag.ID_HK = new SelectList(model.HocKis, "ID", "ID");
            var thongke = model.KHHTs.OrderByDescending(x => x.ID).ToList();
            return View(thongke);
        }
        [HttpPost]
        //Biểu đồ
        public JsonResult ChartData(int hk)
        {
            var noidung = model.KHHTs.Where(item => item.ID_HK == hk).GroupBy(item1 => item1.MonHoc.TenMH).Select(item2 => new { name = item2.Key, count = item2.Count()});
            return Json(new { dbchart = noidung }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ChartC(int hk)
        {
            var sqlconnectionstring = @"data source=tuleap.vanlanguni.edu.vn,18082;initial catalog=SEP24Team15;user id=SEP24Team15;password=Qwerty123456";
            var connnection = new SqlConnection(sqlconnectionstring);
            connnection.Open();
            var command = new SqlCommand();
            command.Connection = connnection;
            command.CommandText = "SELECT COUNT(DISTINCT ID_SV) FROM KHHT WHERE ID_HK = @HK";
            var vHK = new SqlParameter("@HK", hk);
            command.Parameters.Add(vHK);
            var soluong = command.ExecuteScalar();
            connnection.Close();
            return Json(new { dbchart1 = soluong }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult listofExcel()
        {
            List<ThongKeViewModel> khhtList = model.KHHTs.Select(x => new ThongKeViewModel
            {
               
                ID_MH = x.MonHoc.TenMH,               
                ID_SV = x.ID_SV,
                NgayTao = x.NgayTao
            }).ToList();
            return View(khhtList);
        }
        public void ExportToExcel()
        {
            List<ThongKeViewModel> khhtList = model.KHHTs.Select(x => new ThongKeViewModel
            {

                ID_MH = x.MonHoc.TenMH,
                ID_SV = x.AspNetUser.Email,
                NgayTao = x.NgayTao
            }).ToList();

            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Bảng thống kê";
            

            ws.Cells["A2"].Value = "Khoa";
            ws.Cells["B2"].Value = "Công nghệ thông tin";

            
            ws.Cells["A3"].Value = "Ngày in";
            ws.Cells["B3"].Value = string.Format("{0:dd MMMM yyyy} lúc {0:H: mm tt}",DateTimeOffset.Now);

            ws.Cells["A6"].Value = "Tên môn học";
            ws.Cells["B6"].Value = "Mã sinh viên";
            ws.Cells["C6"].Value = "Ngày tạo";

            int rowStart = 7;
            foreach(var item in khhtList)
            {                
                ws.Cells[string.Format("A{0}", rowStart)].Value = item.ID_MH;
                ws.Cells[string.Format("B{0}", rowStart)].Value = item.ID_SV;
                ws.Cells[string.Format("C{0}", rowStart)].Value = item.NgayTao.ToString();
                rowStart++;
            }
            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment: filename =" + "BangThongKe.xlsx");
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();
        }    
    }
}

WebDangKyKHHT/Areas/Admin/Views/ThongKeAdmin/Index.cshtml
@model IEnumerable<WebDangKyKHHT.Models.KHHT>


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/DKKHHTAdmin.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
        function drawChartEachCourse() {
        $(function () {
            var ID_HK = $("#hk").val();
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("ChartData", "ThongKeAdmin")',
                data: JSON.stringify({ hk: ID_HK }),
                success: function (charts) {
                    var data = charts.dbchart;
                    var chartdb = new google.visualization.DataTable();

                    chartdb.addColumn('string', 'Môn học');
                    chartdb.addColumn('number', 'Số lượng sinh viên');


                    for (var i = 0; i < data.length; i++) {
                        chartdb.addRow([data[i].name, data[i].count]);
                    }
                    var options = { 'title': 'Thống kê số lượng sinh viên đăng ký từng môn', is3D: true };
                    var chart = new google.visualization.PieChart(document.getElementById('myChart'));
                    chart.draw(chartdb, options);
                },
            });
        });
    }

    function drawChartStudent() {
        $(function () {
            var ID_HK = $("#hk").val();
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("ChartC", "ThongKeAdmin")',
                data: JSON.stringify({ hk: ID_HK }),
                success: function (charts) {
                    console.log(charts.dbchart1);
                    var data = charts.dbchart1;
                    var chartdb = new google.visualization.DataTable();

                    chartdb.addColumn('string', 'Sinh viên');
                    chartdb.addColumn('number', 'Số lượng');

                    chartdb.addRow(['Đã đăng kí', data]);
                    chartdb.addRow(['Chưa đăng kí', (300 - data)]);
                  
                    var options = { 'title': 'Thống kê số lượng sinh viên đăng ký', is3D: true };
                    var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
                    chart.draw(chartdb, options);
                },
            });
        });
    }
    $(document).ready(function () {
        $("#hk").change(function () {
            google.charts.load('current', { packages: ['corechart'] });
            google.charts.setOnLoadCallback(drawChartStudent);
            google.charts.setOnLoadCallback(drawChartEachCourse);
        });
    });

    
</script>

<!-- Title body -->

<div class="input-group">
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-12">
                            <div class="section-title">
                                <h2>CHỌN HỌC KỲ CHO BIỂU ĐỒ</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-10">
            @Html.DropDownList("hk", (IEnumerable<SelectListItem>)ViewBag.ID_HK, new { @Class = "form-control" })
        </div>

    </div>
    </div>


<div id="piechart_3d" style="width: 900px; height: 500px;"></div>

<div id="myChart" style="width: 900px; height: 500px;"></div>

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>BẢNG THỐNG KÊ MÔN HỌC</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div>
            <button type="button" class="btn btn-secondary" onclick="window.location.href='ThongKeChiTiet'">
                In
            </button>
            <button type="button" class="btn btn-secondary" onclick="window.location.href='ExportToExcel'">
                Xuất Excel
            </button>
        </div>
        <div class="scrollable">
            <table class="table table-striped custom-table">
                <thead>
                    <tr>
                        <th class="service">Mã Môn học</th>
                        <th class="desc">Tên môn học</th>
                        <th>Số tín chỉ</th>
                        <th>Mã học kì</th>
                        <th>Email SV</th>
                        <th>Ngày đăng kí</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MonHoc.MaMH</td>
                            <td>@item.MonHoc.TenMH</td>
                            <td>@item.MonHoc.SoTinChi</td>
                            <td>@item.MonHoc.ID_HK</td>
                            <td>@item.AspNetUser.Email</td>
                            <td>@item.NgayTao</td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>

WebDangKyKHHT/Areas/Admin/Views/ThongKeAdmin/ThongKeChiTiet.cshtml
@model IEnumerable<WebDangKyKHHT.Models.KHHT>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <link href="~/css/Thongke.css" rel="stylesheet" />
</head>
<body>
    <header class="clearfix">
        <div id="logo">
            <img src="~/images/logoVanLang.png" />
        </div>
        <button onclick="window.print()" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-printer" viewBox="0 0 16 16">
                <path d="M2.5 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z" />
                <path d="M5 1a2 2 0 0 0-2 2v2H2a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h1v1a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-1h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-1V3a2 2 0 0 0-2-2H5zM4 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2H4V3zm1 5a2 2 0 0 0-2 2v1H2a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1v-1a2 2 0 0 0-2-2H5zm7 2v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1z" />
            </svg>
        </button>
        <h1>BẢNG THỐNG KÊ</h1>
        <div id="company" class="clearfix">
            <div>Phòng Đào tạo</div>
            <div>C204 – C304<br />103B, Trụ sở 45 Nguyễn Khắc Nhu,P.Cô Giang, Q.1</div>
            <div>028. 3836 4954</div>
            <div><a href="p.daotao@vanlanguni.edu.vn">p.daotao@vanlanguni.edu.vn</a></div>
        </div>
        <div id="project">
            <div><span>PROJECT</span>Bảng thống kê chi tiết kế hoạch học tập</div>
            <div><span>CLIENT</span>Phòng Công Nghệ Thông Tin</</div>
            <div><span>ADDRESS</span>C204 – C304, 233A Phan Văn Trị, P. 11, Q. Bình Thạnh</div>
            <div><span>EMAIL</span> <a href="p.cntt@vanlanguni.edu.vn">p.cntt@vanlanguni.edu.vn</a></div>
            <div><span>DATE</span> August 17, 2015</div>
            <div><span>DUE DATE</span> September 17, 2015</div>
        </div>
    </header>
    <main>
        <table>
            <thead>
                <tr>
                    <th class="service">Mã Môn học</th>
                    <th class="desc">Tên môn học</th>
                    <th>Số tín chỉ</th>
                    <th>Mã học kì</th>
                    <th>ID SV</th>
                    <th>Ngày đăng kí</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                 {
                    <tr>
                        <td>@item.MonHoc.MaMH</td>
                        <td>@item.MonHoc.TenMH</td>
                        <td>@item.MonHoc.SoTinChi</td>
                        <td>@item.MonHoc.ID_HK</td>
                        <td>@item.ID_SV</td>
                        <td>@item.NgayTao</td>
                    </tr>
                 }
            </tbody>
        </table>
        <!--
        <div id="notices">
            <div>NOTICE:</div>
            <div class="notice"></div>
        </div>
        -->
    </main>   
</body>
</html>