WebDangKyKHHT/Models/MonHoc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyKHHT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.KHHTs = new HashSet<KHHT>();
        }
    
        public int ID { get; set; }
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<int> ID_HK { get; set; }
    
        public virtual HocKi HocKi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHHT> KHHTs { get; set; }
    }
}

WebDangKyKHHT/ViewModels/MonHocsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebDangKyKHHT.ViewModels
{
    public class MonHocsViewModel
    {
        

        public int IDMH { get; set; }

        public string TenMH { get; set; }

        public string MaMH { get; set; }

        public int SoTinChi { get; set; }

        public int ID_HK { get; set; }
        
        public bool IsSelected { get; set; }

    }
}

WebDangKyKHHT/Controllers/MonHocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDangKyKHHT.Models;
using WebDangKyKHHT.ViewModels;

namespace WebDangKyKHHT.Controllers
{
    public class MonHocsController : Controller
    {
        private SEP_TEAM15_WEBKHHTEntities db;
        private List<int> MonHoc;
        public MonHocsController()
        {
            db = new SEP_TEAM15_WEBKHHTEntities();
            MonHoc = new List<int>();
        }


        // GET: MonHoc
        public ActionResult Index()
        {
            var dlhk = db.HocKis.ToList();
            List<SelectListItem> idhk = new List<SelectListItem>();
            idhk.Add(new SelectListItem { Value = "", Text = "--Tất cả--", Selected = true });
            foreach (var item in dlhk)
            {
                idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
            }
            ViewBag.ID_HK = idhk;
            return View();
        }

        [HttpPost]
        public JsonResult jsonMH(int? hk)
        {
            var dataMH = (from objMH in db.MonHocs
                          select new MonHocsViewModel()
                          {
                              IDMH = objMH.ID,
                              TenMH = objMH.TenMH,
                              MaMH = objMH.MaMH,
                              SoTinChi = (int)objMH.SoTinChi,
                              ID_HK = (int)objMH.ID_HK,
                              IsSelected = false
                          }).ToList();
            if (Session["monhoc"] != null)
            {
                MonHoc = (List<int>)Session["monhoc"];
            }

            if (MonHoc.Count > 0)
            {
                foreach (var dbrow in MonHoc)
                {
                    var findMH = dataMH.Where(m => m.IDMH == dbrow).FirstOrDefault();
                    if (findMH != null)
                        dataMH.Remove(findMH);
                }
            }
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string sText = Request["search[value]"].ToLower();
            int row = dataMH.Count();
            if (!string.IsNullOrEmpty(sText) && hk != null)
                dataMH = dataMH.Where(m => m.TenMH.ToLower().Contains(sText) && m.ID_HK == hk).ToList();
            else if (!string.IsNullOrEmpty(sText) && hk == null)
                dataMH = dataMH.Where(m => m.TenMH.ToLower().Contains(sText)).ToList();
            else if (string.IsNullOrEmpty(sText) && hk != null)
                dataMH = dataMH.Where(m => m.ID_HK == hk).ToList();
            int rowfilter = dataMH.Count();
            dataMH = dataMH.Skip(start).Take(length).ToList();
            return Json(new { data = dataMH, draw = Request["draw"], recordsTotal = row, recordsFiltered = rowfilter }, JsonRequestBehavior.AllowGet);
        }

        //private SEP_TEAM15_WEBKHHTEntities db = new SEP_TEAM15_WEBKHHTEntities();

        //// GET: MonHocs
        //[AllowAnonymous]
        //public ActionResult Index()
        //{
        //    var dlhk = db.HocKis.ToList();
        //    List<SelectListItem> idhk = new List<SelectListItem>();
        //    idhk.Add(new SelectListItem { Value = "", Text = "--Tất cả--", Selected = true });
        //    foreach (var item in dlhk)
        //    {
        //        idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
        //    }
        //    ViewBag.ID_HK = idhk;
        //    //ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID");
        //    var monHocs = db.MonHocs.Include(m => m.HocKi);
        //    return View(monHocs.ToList());

        //}
        //[HttpPost]
        //public ActionResult Index(int ID_HK)
        //{
        //    var dlhk = db.HocKis.ToList();
        //    List<SelectListItem> idhk = new List<SelectListItem>();
        //    idhk.Add(new SelectListItem { Value = "", Text = "--Tất cả--", Selected = true });
        //    foreach (var item in dlhk)
        //    {
        //        idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
        //    }
        //    ViewBag.ID_HK = idhk;
        //    //ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID");
        //    var monHocs = db.MonHocs.Include(m => m.HocKi).Where(a => a.ID_HK == ID_HK);
        //    return View(monHocs.ToList());

        //}

        // GET: MonHocs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            return View(monHoc);
        }

        // GET: MonHocs/Create
        public ActionResult Create()
        {
            ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID");
            return View();
        }

        // POST: MonHocs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MaMH,TenMH,SoTinChi,ID_HK")] MonHoc monHoc)
        {
            if (ModelState.IsValid)
            {
                db.MonHocs.Add(monHoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID", monHoc.ID_HK);
            return View(monHoc);
        }

        // GET: MonHocs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID", monHoc.ID_HK);
            return View(monHoc);
        }

        // POST: MonHocs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MaMH,TenMH,SoTinChi,ID_HK")] MonHoc monHoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monHoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_HK = new SelectList(db.HocKis, "ID", "ID", monHoc.ID_HK);
            return View(monHoc);
        }

        // GET: MonHocs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            return View(monHoc);
        }

        // POST: MonHocs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MonHoc monHoc = db.MonHocs.Find(id);
            db.MonHocs.Remove(monHoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [AllowAnonymous]
        public ActionResult Search(string HK)
        {
            var monhoc = db.MonHocs.ToList();           
            int iHK = int.Parse(HK);
            monhoc = monhoc.Where(m => m.HocKi.TenHK == iHK).ToList();
            return View("Index", monhoc);
        }
        
    }
}

WebDangKyKHHT/Views/MonHocs/Create.cshtml
@model WebDangKyKHHT.Models.MonHoc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/DKKHHT.cshtml";
}
<br />
<br />
<br />
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Tạo Môn Học</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.MaMH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaMH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenMH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoTinChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ID_HK, "ID_HK", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ID_HK", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ID_HK, "", new { @class = "text-danger" })



                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebDangKyKHHT/Views/MonHocs/Delete.cshtml
@model WebDangKyKHHT.Models.MonHoc

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonHoc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTinChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HocKi.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HocKi.ID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebDangKyKHHT/Views/MonHocs/Details.cshtml
@model WebDangKyKHHT.Models.MonHoc

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MonHoc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTinChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HocKi.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HocKi.ID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebDangKyKHHT/Views/MonHocs/Edit.cshtml
@model WebDangKyKHHT.Models.MonHoc

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MonHoc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.MaMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoTinChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_HK, "ID_HK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_HK", null, htmlAttributes: new { @class = "form-control" })               
                @Html.ValidationMessageFor(model => model.ID_HK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebDangKyKHHT/Views/MonHocs/Index.cshtml
@model IEnumerable<WebDangKyKHHT.Models.MonHoc>
@using Microsoft.AspNet.Identity


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/DKKHHT.cshtml";

}
<link href="@Url.Content("~/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>
<script src="@Url.Content("~/js/jquery.dataTables.min.js")"></script>
<script src="@Url.Content("~/js/dataTables.bootstrap4.min.js")"></script>
<script>
    jQuery(document).ready(function ($) {
        var table = $('#tbMonHoc').DataTable({
            "lengthMenu": [10, 20, 100, 200],
            "ordering": false,
            "language": {
                "decimal": "",
                "emptyTable": "Không có dữ liệu",
                "info": "Hiện từ _START_ tới _END_ trong _TOTAL_ dòng",
                "infoEmpty": "Hiện từ 0 tới 0 trong 0 dòng",
                "infoFiltered": "(tìm kiếm từ _MAX_)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Hiển thị _MENU_ dòng",
                "loadingRecords": "Đảng tải xuống...",
                "processing": "Đang xử lý...",
                "search": "Tìm kiếm:",
                "zeroRecords": "Không tìm thấy dữ liệu",
                "paginate": {
                    "first": "&laquo;",
                    "last": "&raquo;",
                    "next": "&rsaquo;",
                    "previous": "&lsaquo;"
                },
                "select": {
                    "rows": {
                        _: 'Đã chọn %d dòng',
                        0: ''
                    }
                }
            },
            "ajax": {
                "url": '@Url.Action("jsonMH", "MonHocs")',
                "type": "POST",
                "data": function (d) {
                    d.hk = $("#hk option:selected").val();
                },
                "datatype": "json"
            },
            "columns": [
                { "data": "TenMH", "name": "TenMH" },
                { "data": "MaMH", "name": "MaMH" },
                { "data": "SoTinChi", "name": "SoTinChi" },
                { "data": "ID_HK", "name": "ID_HK" },
                
            ],
            "serverSide": "true",
            "processing": "true"
        });
        $('#hk').on('change', function () {
            table.ajax.reload();
        });
    });
        </script>
<style>
    .scrollable {
        height: 480px;
        overflow: scroll;
    }

        .scrollable table thead th {
            position: sticky;
            top: 0;
            background-color: white;
        }

    .table-fixed tr {
        display: block;
    }
</style>


<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>CHƯƠNG TRÌNH ĐÀO TẠO</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4 text-right">
                <div class="input-group">
                    Học kỳ: @Html.DropDownList("hk", (IEnumerable<SelectListItem>)ViewBag.ID_HK, new { @Class = "form-control" })
                </div>
            </div>
            <div class="col-12">
                <table class="table table-striped custom-table" id="tbMonHoc" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Tên môn</th>
                            <th>Mã môn</th>
                            <th>Số tín chỉ</th>
                            <th>Học kì</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

    @*<div class="content">
        <div class="container">
            <div class="d-flex align-items-center">

                @using (Html.BeginForm())
                {
                    <table>
                        <tr>
                            <th>
                                Chọn Học Kì
                            </th>
                            <th>
                                @Html.DropDownList("ID_HK", null, htmlAttributes: new { @class = "form-control" })
                            </th>
                            <th>
                                &ensp;
                                <button class="btn btn-secondary" type="submit" value="Tìm kiếm" /><span>Tìm kiếm</span>
                            </th>

                            <th>
                                @if (User.IsInRole("Admin"))
                                {

                                    <a id="collapseTwo" aria-labelledby="headingOne" href="@Url.Content("~/MonHocs/Create")" class="nav-link text-left">Tạo Môn</a>

                                }
                            </th>
                        </tr>
                    </table>
                }
            </div>
        </div>
        <div class="container">
            <div class="scrollable">
                <table class="table table-striped custom-table">
                    <thead>
                        <tr>
                            <th scope="col">Số thứ tự</th>
                            <th scope="col">Tên môn</th>
                            <th scope="col">Mã môn</th>
                            <th scope="col">Học kỳ</th>
                            <th scope="col">Số tín chỉ</th>
                            @if (User.IsInRole("Admin"))
                            {
                                <th scope="col">Sửa Môn</th>
                                <th scope="col">Xóa Môn</th>
                            }

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            {
                                total += (int)item.SoTinChi;
                                <tr scope="row">
                                    <td>@item.ID</td>
                                    <td><p>@item.TenMH</p></td>
                                    <td>
                                        @item.MaMH
                                    </td>
                                    <td>@item.HocKi.TenHK</td>
                                    <td>@item.SoTinChi</td>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <td> @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) </td>
                                        <td> @Html.ActionLink("Xóa", "Delete", new { id = item.ID }) </td>
                                    }
                                </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
    </div>
        <div class="container">
            <table class="table table-striped table-borderless">
                <thead>
                    <tr>
                        <th scope="col">Tổng số tín chỉ</th>
                    </tr>
                </thead>
                <tbody align="center">
                    <tr>
                        <td>
                            @total
                        </td>
                    </tr>
                </tbody>

            </table>
        </div>
    </div>
</div>*@