WebDangKyKHHT/Controllers/DangKyKHHTController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebDangKyKHHT.Models;
using WebDangKyKHHT.ViewModels;



namespace WebDangKyKHHT.Controllers
{

    public class DangKyKHHTController : Controller
    {
        private SEP_TEAM15_WEBKHHTEntities db;
        private List<int> MonHoc;

        public DangKyKHHTController()
        {
            db = new SEP_TEAM15_WEBKHHTEntities();
            MonHoc = new List<int>();

        }
        public ActionResult ThongBao()
        {
            return View();
        }
        [Authorize]
        // GET: DangKyKHHT
        public ActionResult Index()
        {
            var dlhk = db.HocKis.ToList();
            List<SelectListItem> idhk = new List<SelectListItem>();
            idhk.Add(new SelectListItem { Value = "", Text = "--Tất cả--", Selected = true });
            foreach (var item in dlhk)
            {
                idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
            }
            ViewBag.ID_HK = idhk;
            var deadline = db.Deadlines.Where(m => m.ID == 1).FirstOrDefault();
            if (DateTimeOffset.Now >= deadline.DateStart && DateTimeOffset.Now <= deadline.DateEnd)
            {
                return View();
            }
            else
            {
                return RedirectToAction("ThongBao");
            }
            //if(deadline.Dangky == true)
            //{
            //    return View();
            //}
            //else
            //{
            //    return RedirectToAction("ThongBao");
            //}            
        }

        [HttpPost]
        public JsonResult jsonMH(int? hk)
        {
            var dataMH = (from objMH in db.MonHocs
                          select new MonHocsViewModel()
                          {
                              IDMH = objMH.ID,
                              TenMH = objMH.TenMH,
                              MaMH = objMH.MaMH,
                              SoTinChi = (int)objMH.SoTinChi,
                              ID_HK = (int)objMH.ID_HK,
                              IsSelected = false
                          }).ToList();
            if (Session["monhoc"] != null)
            {
                MonHoc = (List<int>)Session["monhoc"];
            }

            if (MonHoc.Count > 0)
            {
                foreach (var dbrow in MonHoc)
                {
                    var findMH = dataMH.Where(m => m.IDMH == dbrow).FirstOrDefault();
                    if (findMH != null)
                        dataMH.Remove(findMH);
                }
            }
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string sText = Request["search[value]"].ToLower();
            int row = dataMH.Count();
            if (!string.IsNullOrEmpty(sText) && hk != null)
                dataMH = dataMH.Where(m => m.TenMH.ToLower().Contains(sText) && m.ID_HK == hk).ToList();
            else if (!string.IsNullOrEmpty(sText) && hk == null)
                dataMH = dataMH.Where(m => m.TenMH.ToLower().Contains(sText)).ToList();
            else if (string.IsNullOrEmpty(sText) && hk != null)
                dataMH = dataMH.Where(m => m.ID_HK == hk).ToList();
            int rowfilter = dataMH.Count();
            dataMH = dataMH.Skip(start).Take(length).ToList();
            return Json(new { data = dataMH, draw = Request["draw"], recordsTotal = row, recordsFiltered = rowfilter }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult addKhht(int idMH)
        {
            if (Session["monhoc"] != null)
                MonHoc = (List<int>)Session["monhoc"];
            MonHoc.Add(idMH);
            Session["monhoc"] = MonHoc;
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            var dlhk = db.HocKis.ToList();
            List<SelectListItem> idhk = new List<SelectListItem>();
            idhk.Add(new SelectListItem { Value = "", Text = "Chọn học kỳ", Selected = true });
            foreach (var item in dlhk)
            {
                idhk.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.TenHK.ToString() });
            }
            ViewBag.ID_HK = idhk;

            if (Session["monhoc"] != null)
                MonHoc = (List<int>)Session["monhoc"];
            var vdb = GetMH(MonHoc);
            return View(vdb);
        }

        [HttpPost]
        public JsonResult removeMH(int? MaMH)
        {
            try
            {
                if (MaMH != null)
                {
                    if (Session["monhoc"] != null)
                        MonHoc = (List<int>)Session["monhoc"];
                    bool result = MonHoc.Remove((int)MaMH);
                    if (result)
                    {
                        Session["monhoc"] = MonHoc;
                        return Json(new { success = true }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch { }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult edit(List<int> MaMH, int? hk)
        {
            try
            {
                if (hk == null)
                {
                    TempData["notify"] = "<div class=\"alert alert-danger\" role=\"alert\">Bạn chưa chọn học kỳ</div>";
                    return RedirectToAction("Edit");
                }
                string ID_SV = User.Identity.GetUserId();
                if (MaMH != null)
                {
                    if (MaMH.Count > 0)
                    {
                        var datatemp = GetMH(MaMH);
                        int tSoTinChi = 0;
                        foreach (var dl in datatemp)
                        {
                            tSoTinChi += dl.SoTinChi;
                        }
                        if (tSoTinChi >= 12 && tSoTinChi <= 20)
                        {
                            db.KHHTs.RemoveRange(db.KHHTs.Where(m => m.ID_SV == ID_SV && m.ID_HK == hk));
                            foreach (var item in MaMH)
                            {
                                KHHT objKHHT = new KHHT();
                                objKHHT.ID_SV = ID_SV;
                                objKHHT.ID_MH = item;
                                objKHHT.NgayTao = DateTime.Now;
                                objKHHT.ID_HK = hk;
                                db.KHHTs.Add(objKHHT);
                            }
                            db.SaveChanges();
                            Session["monhoc"] = null;
                            TempData["notify"] = "<div class=\"alert alert-success\" role=\"alert\">Lưu dữ liệu thành công</div>";
                        }
                        else
                            TempData["notify"] = "<div class=\"alert alert-danger\" role=\"alert\">Tổng số tín phải trong khoảng 12 đến 20 tín chỉ</div>";
                    }
                }
                else
                {
                    var objKHHT = db.KHHTs.RemoveRange(db.KHHTs.Where(m => m.ID_SV == ID_SV && m.ID_HK == hk));
                    db.SaveChanges();
                    Session["monhoc"] = null;
                    TempData["notify"] = "<div class=\"alert alert-danger\" role=\"alert\">KHHT của học kì bạn chọn đã bị xóa</div>";
                }
            }
            catch
            {
                TempData["notify"] = "<div class=\"alert alert-danger\" role=\"alert\">Lỗi dữ liệu vui lòng kiểm tra lại</div>";
            }
            return RedirectToAction("Edit");
        }

        protected List<MonHocsViewModel> GetMH(List<int> idMH)
        {
            var dataMH = (from objMH in db.MonHocs
                          select new MonHocsViewModel()
                          {
                              IDMH = objMH.ID,
                              TenMH = objMH.TenMH,
                              MaMH = objMH.MaMH,
                              SoTinChi = (int)objMH.SoTinChi,
                              ID_HK = (int)objMH.ID_HK,
                              IsSelected = false
                          }).ToList();
            List<MonHocsViewModel> datatemp = new List<MonHocsViewModel>();
            for (int i = 0; i < dataMH.Count; i++)
            {
                foreach (var ma in idMH)
                {
                    if (dataMH[i].IDMH == ma)
                        datatemp.Add(dataMH[i]);
                }
            }
            return datatemp;
        }
    }
}

WebDangKyKHHT/Views/DangKyKHHT/Edit.cshtml
@model List<WebDangKyKHHT.ViewModels.MonHocsViewModel>
@using Microsoft.AspNet.Identity


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/DKKHHT.cshtml";
}
<script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>
<script>
    jQuery(document).ready(function ($) {
        $('.btn-del').click(function (e) {
            e.preventDefault();
            o = $(this);
            stcm1 = o.data('tstc');
            idMH = $(this).data("mamh");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("removeMH", "DangKyKHHT")',
                data: { MaMH: idMH },
                success: function (data) {
                    if (data.success) {
                        o.parents('tr').remove();
                        var i = 0;
                        $('.MaMH').each(function () {
                            $(this).attr('name', 'MaMH[' + i + ']');
                            i++;
                        });
                        var tstc = $('.tstc').data('tstc');
                        tstc = tstc - stcm1;
                        $('.tstc').data('tstc', tstc);
                        $('.tstc').html(tstc);
                    }
                }
            });
        });
    });
</script>
<!-- Title body -->
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>BẢNG ĐĂNG KÝ KẾ HOẠCH HỌC TẬP</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();
        <div class="container">
            <div class="row">
                <div class="col-12">
                    @Html.Raw(TempData["notify"])
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                    <button class="btn btn-primary" type="submit">Lưu</button>
                </div>
                <div class="col-4">
                    Học kỳ: @Html.DropDownList("hk", (IEnumerable<SelectListItem>)ViewBag.ID_HK, new { @Class = "form-control" })
                </div>
                <div class="col-12">
                    <table class="table custom-table" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Tên môn</th>
                                <th>Mã môn</th>
                                <th>Số tín chỉ</th>
                                <th></th>
                            </tr>
                        </thead>
                        @if (Model.Count != 0)
                        {
                            <tbody>
                                @{int total = 0;}
                                @for (int i = 0; i < Model.Count; i++)
                                {
                                    total += Model[i].SoTinChi;
                                    <tr>
                                        <td>@Html.Raw(Model[i].TenMH)</td>
                                        <td>
                                            @Html.Raw(Model[i].MaMH)
                                            <input class="MaMH" hidden name="MaMH[@(i)]" value="@(Model[i].IDMH)" />
                                        </td>
                                        <td>@Html.Raw(Model[i].SoTinChi)</td>
                                        <td><button class="btn btn-danger btn-sm btn-del" data-MaMH="@(Model[i].IDMH)" data-tstc="@(Model[i].SoTinChi)">Xóa</button></td>
                                    </tr>
                                }
                                <tr>
                                    <td colspan="2">Tổng số tín chỉ</td>
                                    <td colspan="2" class="tstc" data-tstc="@total">@total</td>
                                </tr>
                            </tbody>
                        }
                    else
                    {
                        <tbody>
                            <tr>
                                <td colspan="4" align="center">Chưa chọn môn, chọn lưu sẽ xóa KHHT đã đăng ký cho học kì bạn chọn</td>
                            </tr>                                                         
                        </tbody>
                    }

                    </table>
                </div>
            </div>
        </div>
    }
</div>

WebDangKyKHHT/Views/DangKyKHHT/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/DKKHHT.cshtml";
}
<link href="@Url.Content("~/css/dataTables.bootstrap4.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>
<script src="@Url.Content("~/js/jquery.dataTables.min.js")"></script>
<script src="@Url.Content("~/js/dataTables.bootstrap4.min.js")"></script>


<script>
    jQuery(document).ready(function ($) {
        var table = $('#tbMonHoc').DataTable({
            "lengthMenu": [7, 20, 30, 100],
            "ordering": false,
            "language": {
                "decimal": "",
                "emptyTable": "Không có dữ liệu",
                "info": "Hiện từ _START_ tới _END_ trong _TOTAL_ dòng",
                "infoEmpty": "Hiện từ 0 tới 0 trong 0 dòng",
                "infoFiltered": "(tìm kiếm từ _MAX_)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Hiển thị _MENU_ dòng",
                "loadingRecords": "Đảng tải xuống...",
                "processing": "Đang xử lý...",
                "search": "Tìm kiếm:",
                "zeroRecords": "Không tìm thấy dữ liệu",
                "paginate": {
                    "first": "&laquo;",
                    "last": "&raquo;",
                    "next": "&rsaquo;",
                    "previous": "&lsaquo;"
                },
                "select": {
                    "rows": {
                        _: 'Đã chọn %d dòng',
                        0: ''
                    }
                }
            },
            "ajax": {
                "url": '@Url.Action("jsonMH", "DangKyKHHT", new { })',
                "type": "POST",
                "data": function (d) {
                    d.hk = $("#hk option:selected").val();
                },
                "datatype": "json"
            },
            "columns": [
                { "data": "TenMH", "name": "TenMH" },
                { "data": "MaMH", "name": "MaMH" },
                { "data": "SoTinChi", "name": "SoTinChi" },
                { "data": "ID_HK", "name": "ID_HK" },
                {
                    "data": "IDMH",
                    "render": function (data) {
                        return '<a class="btn btn-danger btnchoose" href="#" data-idmh="' + data + '" style = "color: #fff">Chọn</a>'
                    }
                }
            ],
            "serverSide": "true",
            "processing": "true"
        });
        $('#hk').on('change', function () {
            table.ajax.reload();
        });
        $('#tbMonHoc').on('click', '.btnchoose', function (e) {
            e.preventDefault();
            idmh = $(this).data("idmh");
            dr = table.row($(this).parents('tr'))
            $.ajax({
                type: 'POST',
                url: '@Url.Action("addKhht", "DangKyKHHT")',
                data: { idMH: idmh },
                success: function (data) {
                    if (data.success) {
                        dr.remove().draw();
                    }
                }
            });
        });
    });

</script>


<!-- Title body -->
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>BẢNG ĐĂNG KÝ KẾ HOẠCH HỌC TẬP</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8">
                <a class="btn btn-danger" href="@Url.Content("~/chinh-sua-dang-ky")">Môn đã chọn</a>
            </div>
            <div class="col-4 text-right">
                <div class="input-group">
                    Học kỳ: @Html.DropDownList("hk", (IEnumerable<SelectListItem>)ViewBag.ID_HK, new { @Class = "form-control" })
                </div>
            </div>
            <div class="col-12">
                <table class="table custom-table" id="tbMonHoc" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th scope="col">Tên môn</th>
                            <th scope="col">Mã môn</th>
                            <th scope="col">Số tín chỉ</th>
                            <th scope="col">Học kì</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

WebDangKyKHHT/Views/DangKyKHHT/ThongBao.cshtml
@{
    ViewBag.Title = "ThongBao";
}

<h2>ThongBao</h2>
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>CHƯA ĐẾN THỜI GIAN ĐĂNG KÝ</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>